server:
  port: 8080
  servlet:
    context-path: "/cep-api"

external:
    api:
      cep: "viacep.com.br/ws/"
      ibge: "https://servicodados.ibge.gov.br/api/v1/localidades/municipios/"

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

freight:
  sudeste: 7.85
  centroOeste: 12.50
  nordeste: 15.98
  sul: 17.30
  norte: 20.83